const catalogProducts = [
    {
        id: "id0",
        name: "Need for Speed: Rivals",
        image: "./images/img_1.jpg",
        price: "200 BYN",
        imageSlider: ["./images/sliderProducts/NeedForSpeedRivals/img0.jpeg",
            "./images/sliderProducts/NeedForSpeedRivals/img1.jpg",
            "./images/sliderProducts/NeedForSpeedRivals/img2.jpg",
            "./images/sliderProducts/NeedForSpeedRivals/img3.jpg",
            "./images/sliderProducts/NeedForSpeedRivals/img4.jpg",
            "./images/sliderProducts/NeedForSpeedRivals/img5.jpg",],
        description: "Добро пожаловать на залитые солнцем улицы Майами Палме! Здесь асфальт плавится не только от знойной жары, но и от покрышек отчаянных гонщиков, которые практикуются днём и ночью! Купить Need for Speed: Heat – это отличный способ присоединиться к ним! Днём они собирают толпы зевак у заграждений, состязаясь в официальных дисциплинах, до которых полиции нет дела, но ночью у полиции прибавляется работёнки, когда гонщики решаются развлечься в уличных гонках, где за ними не могут наблюдать спонсоры. Станьте королём обоих гоночных миров!"
    },
    {
        id: "id1",
        name: "Need for Speed: Heat",
        image: "./images/img_2.jpg",
        price: "100 BYN",
        sale: "-50%",
        imageSlider: ["./images/sliderProducts/NeedForSpeedHeat/img0.jpg",
            "./images/sliderProducts/NeedForSpeedHeat/img1.png",
            "./images/sliderProducts/NeedForSpeedHeat/img2.jpg",
            "./images/sliderProducts/NeedForSpeedHeat/img3.jpg",
            "./images/sliderProducts/NeedForSpeedHeat/img4.jpg",
            "./images/sliderProducts/NeedForSpeedHeat/img5.jpg",],

    },
    {
        id: "id2",
        name: "Need for Speed: PayBack",
        image: "./images/img_3.jpeg",
        price: "150 BYN",
        imageSlider: ["./images/sliderProducts/NeedForSpeedPayBack/img0.jpg",
            "./images/sliderProducts/NeedForSpeedPayBack/img1.jpg",
            "./images/sliderProducts/NeedForSpeedPayBack/img2.jpg",
            "./images/sliderProducts/NeedForSpeedPayBack/img3.jpg",
            "./images/sliderProducts/NeedForSpeedPayBack/img4.jpg",
            "./images/sliderProducts/NeedForSpeedPayBack/img5.jpg",],
    },
    {
        id: "id3",
        name: "Need for Speed: NoLimits",
        image: "./images/img_4.jpg",
        price: "300 BYN",
        sale: "-15%",
        imageSlider: ["./images/sliderProducts/NeedForSpeedNoLimits/img0.jpg",
            "./images/sliderProducts/NeedForSpeedNoLimits/img1.jpg",
            "./images/sliderProducts/NeedForSpeedNoLimits/img2.jpg",
            "./images/sliderProducts/NeedForSpeedNoLimits/img3.jpg",
            "./images/sliderProducts/NeedForSpeedNoLimits/img4.jpg",
            "./images/sliderProducts/NeedForSpeedNoLimits/img5.jpg",],
    },
    {
        id: "id4",
        name: "Need for Speed: Underground2",
        image: "./images/img_5.jpg",
        price: "50 BYN",
        imageSlider: ["./images/sliderProducts/NeedForSpeedUnderground2/img0.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground2/img1.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground2/img2.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground2/img3.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground2/img4.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground2/img5.jpg",],
    },
    {
        id: "id5",
        name: "Need for Speed: Underground1",
        image: "./images/img_6.jpg",
        price: "20 BYN",
        imageSlider: ["./images/sliderProducts/NeedForSpeedUnderground1/img0.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground1/img1.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground1/img2.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground1/img3.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground1/img4.jpg",
            "./images/sliderProducts/NeedForSpeedUnderground1/img5.jpg",],
    },
];
